"""
visualization.py
----------------
Visualization methods to view images and clusters
"""
import argparse
import math
import matplotlib.pyplot as plt
import os
import pandas as pd
import sys
from PIL import Image

def generate_image(paths: list, size:list=[56,56]) -> Image:
    dims = math.ceil(math.sqrt(len(paths)))
    dst = Image.new("RGB", (size[0], size[1]))
    img_size = (size[0]//dims, size[1]//dims)

    for i, path in enumerate(paths):
        indx = i%dims
        img = Image.open(path).resize(img_size)
        dst.paste(img, (img_size[0]*(i%dims), img_size[1]*(i//dims)))
    return dst

def view_all_clusters(df:pd.DataFrame, fname:str, colname:str, img_size:list=[2048,2048]) -> None:
    BORDER_SIZE = 20
    clusters = df[colname].unique()
    cdims = math.ceil(math.sqrt(len(clusters)))

    # Create target image
    dst = Image.new("RGB", img_size)

    # Calculate dims after considering borders
    borders = BORDER_SIZE*(cdims-1)
    cell_size = ((img_size[0]-borders)//cdims, (img_size[1]-borders)//cdims)

    # Generate image per cluster
    for i, cluster in enumerate(clusters):
        # Get paths of cluster
        paths = df[df[colname] == cluster]["path"].tolist()
        img = generate_image(paths, size=cell_size)
        
        # Calculate img location
        x = cell_size[0]*(i%cdims) + (i%cdims)*BORDER_SIZE
        y = cell_size[1]*(i//cdims) + (i//cdims)*BORDER_SIZE

        dst.paste(img, (x,y))
    dst.save(fname)

def main(args):
    df = pd.read_csv(args.file)
    folder = os.path.splitext(args.file)[0] if args.folder is None else args.folder

    # Make folder if it does not exist
    if not os.path.isdir(folder):
        os.mkdir(folder)

    for col in df:
        if col not in ["path", "label", "Unnamed: 0"]:
            view_all_clusters(df, os.path.join(folder, col+".png"), col)

if __name__ == "__main__":
    # Define argument parser
    parser = argparse.ArgumentParser(
        description="Make an image visualization of each cluster generated by a test."
    )
    parser.add_argument("-f", "--file", type=str, required=True,
        help="The csv file path in which the clusters will be saved at.")
    parser.add_argument("-o", "--folder", type=str,
        help="Specify the folder in which the output images are going to be saved.")
    main(parser.parse_args())
